[package]
name = "state-capitals-quiz-yew"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] } # needed for rand on wasm
web-sys = { version = "0.3", features = ["HtmlInputElement"] }